### ISSUE TITLE
All Health Record - Clicking on the '+' icon on the Health Parameter screen shows a wrong message

### ISSUE THREAD

**Issue by shanthasprim** [Sprim/DGC-Android#11]
## Steps To Reproduce:
1. Click on any Health parameter under the Health Records section.
2. Click on the '+' icon in the right top of the screen.
## Actual Result:

A Pop-up window is displayed as "What do you want tio dop?"
## Expected Result:

Pop-up window should be displayed as "What do you want to do?"
## Precondition:

NA

**Comment by hanusprim** [comment]
Issue Solved

**Comment by shanthasprim** [comment]
working as Expected
