### ISSUE TITLE
The Health Record - BP Health Parameter shows the Empty Goal value when the Goal value is not set

### ISSUE THREAD

**Issue by shanthasprim** [Sprim/DGC-Android#24]
## Steps To Reproduce:
1. Open the app with any log in.
2. Click the BP Health parameter under the Health Records section.
3. Check below the X-axis in the Graph.
## Actual Result:

The Systolic Diastolic value is displayed as ------  ------
## Expected Result:

The Systolic Diastolic value should be displayed only when the Goal value is set and empty value should not be displayed.
## Precondition:
1. No Goal value is set
2. BP track value entered

**Comment by hanusprim** [comment]
Issue Resolved

**Comment by shanthasprim** [comment]
Working as Expected.
