### ISSUE TITLE
Food Tracker - Entering Food Value for any other date other than the present day the values are taken for the date 01, Jan 1970

### ISSUE THREAD

**Issue by shanthasprim** [Sprim/DGC-Android#30]
## Steps To Reproduce:
1. Open the Food Tracker screen from the left menu.
2. Enter any value for food by clicking '+' icon and select any date lesser than the present day.
## Actual Result:

The food value is recorded with the date 01, Jan 1970 when the date for the food value is selected as any other value other than the present day.
## Expected Result:

Correct date selected should be taken and recorded in the Food history

**Comment by hanusprim** [comment]
Issue Resolved

**Comment by shanthasprim** [comment]
Working as Expected
