### ISSUE TITLE
All Health Records - Change the Text from "What do you want to tio dop?" to "What do you want to do?" on clicking the '+' icon

### ISSUE THREAD

**Issue by shanthasprim** [Sprim/DGC-Android#32]
## Steps To Reproduce:
1. Open Health Tracker from the left menu.
2. Open any health Parameter. 
3. Click on the '+' icon on the right top corner
## Actual Result:

The alert opens as  "What do you want to tio dop?"
## Expected Result:

change the text from "What do you want to tio dop?" to "What do you want to do?"

**Comment by hanusprim** [comment]
Issue Resolved

**Comment by shanthasprim** [comment]
Test Changed hence closing this issue.
