### ISSUE TITLE
BMI Calculation is not correct

### ISSUE THREAD

**Issue by mghipparagi** [Sprim/DGC-Android#6]
## Steps To Reproduce
1. Enter the “Age” value.
2. Enter a valid value in “Height” field.
3. Enter a valid value in “Weight” field.
## Actual Result

BMI value is displayed wrongly
## Expected Result

Correct BMI value should be displayed
## Comments

BMI value calculation is not correct

**Comment by hanusprim** [comment]
Issue Solved

**Comment by shanthasprim** [comment]
Working as Expected.
